-- ==============================================================================
-- VPSA YOGA - Complete Supabase PostgreSQL Schema & Security Migration Script
-- Run this complete script in the Supabase Dashboard SQL Editor (https://supabase.com/dashboard)
-- ==============================================================================

-- 0. Enable Cryptographic Extension for RFC 6238 TOTP Verification
CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- ==============================================================================
-- 1. Create Inquiries Table (Server-Validated & Protected)
-- ==============================================================================
CREATE TABLE IF NOT EXISTS public.inquiries (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name TEXT NOT NULL,
    email TEXT NOT NULL,
    country_code TEXT DEFAULT '+91',
    mobile_number TEXT NOT NULL,
    company_name TEXT,
    product_variety TEXT,
    quantity TEXT,
    destination TEXT,
    message TEXT NOT NULL,
    status TEXT DEFAULT 'new' CHECK (status IN ('new', 'contacted', 'in_review', 'completed')),
    ip_address TEXT,
    bot_honey TEXT,
    dpdp_consent BOOLEAN DEFAULT TRUE NOT NULL,
    consent_text_version TEXT DEFAULT 'dpdp-v1',
    dpdp_consent_timestamp TIMESTAMPTZ DEFAULT NOW(),
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Ensure all columns exist if the table was created previously
ALTER TABLE public.inquiries ADD COLUMN IF NOT EXISTS bot_honey TEXT;
ALTER TABLE public.inquiries ADD COLUMN IF NOT EXISTS dpdp_consent BOOLEAN DEFAULT TRUE;
ALTER TABLE public.inquiries ADD COLUMN IF NOT EXISTS dpdp_consent_timestamp TIMESTAMPTZ DEFAULT NOW();
ALTER TABLE public.inquiries ADD COLUMN IF NOT EXISTS consent_text_version TEXT DEFAULT 'dpdp-v1';

-- ==============================================================================
-- 2. Performance Indexes
-- ==============================================================================
CREATE INDEX IF NOT EXISTS idx_inquiries_status ON public.inquiries(status);
CREATE INDEX IF NOT EXISTS idx_inquiries_created ON public.inquiries(created_at DESC);

-- ==============================================================================
-- 3. Server-Side Validation Trigger Function (Supabase Enforces All Rules)
-- ==============================================================================
CREATE OR REPLACE FUNCTION public.fn_validate_inquiry()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
    v_domain TEXT;
BEGIN
    -- 1. Honeypot Bot Shield (Safe jsonb access)
    IF (to_jsonb(NEW) ? 'bot_honey') AND trim(coalesce(to_jsonb(NEW) ->> 'bot_honey', '')) <> '' THEN
        RAISE EXCEPTION 'Bot submission detected and rejected.';
    END IF;

    -- 2. Normalize and Trim Fields
    NEW.full_name := trim(coalesce(NEW.full_name, ''));
    NEW.email := lower(trim(coalesce(NEW.email, '')));
    NEW.mobile_number := trim(coalesce(NEW.mobile_number, ''));
    NEW.message := trim(coalesce(NEW.message, ''));
    NEW.company_name := nullif(trim(coalesce(NEW.company_name, '')), '');
    NEW.product_variety := nullif(trim(coalesce(NEW.product_variety, '')), '');
    NEW.quantity := nullif(trim(coalesce(NEW.quantity, '')), '');
    NEW.destination := nullif(trim(coalesce(NEW.destination, '')), '');

    -- 3. Length Validations
    IF char_length(NEW.full_name) < 2 OR char_length(NEW.full_name) > 100 THEN
        RAISE EXCEPTION 'Full name must be between 2 and 100 characters.';
    END IF;

    IF char_length(NEW.message) < 5 OR char_length(NEW.message) > 2000 THEN
        RAISE EXCEPTION 'Inquiry message must be between 5 and 2000 characters.';
    END IF;

    -- 4. Email Format Validation
    IF NOT (NEW.email ~* '^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}$') THEN
        RAISE EXCEPTION 'Please provide a valid email address.';
    END IF;

    -- 5. Disposable / Temporary Email Blacklist (Enforced on Database)
    v_domain := split_part(NEW.email, '@', 2);
    IF v_domain IN (
        '10minutemail.com', '10minutemail.net', 'tempmail.com', 'tempmail.net', 'temp-mail.org',
        'mailinator.com', 'guerrillamail.com', 'guerrillamailblock.com', 'guerrillamail.org',
        'guerrillamail.biz', 'guerrillamail.info', 'grr.la', 'sharklasers.com', 'throwawaymail.com',
        'yopmail.com', 'yopmail.net', 'dispostable.com', 'trashmail.com', 'trashmail.net',
        'getairmail.com', 'mohmal.com', 'maildrop.cc', 'mintemail.com', 'fakeinbox.com',
        'fakemailgenerator.com', 'crazymailing.com', 'generator.email', 'tempinbox.com',
        'mytemp.email', 'inboxbear.com', 'emailondeck.com', 'burnermail.io', 'getnada.com',
        'abcvg.com', 'dropmail.me', 'tempail.com', 'clipmail.eu', 'moakt.com', 'mytempemail.com',
        'nada.ltd', 'inboxkitten.com', 'spam4.me', 'trashmail.de', 'tempmailaddress.com'
    ) THEN
        RAISE EXCEPTION 'Disposable temporary email addresses are not permitted. Please use a valid email.';
    END IF;

    -- 6. Phone Number Validation (7 to 20 valid characters)
    IF NOT (NEW.mobile_number ~ '^[0-9+()\- ]{7,20}$') THEN
        RAISE EXCEPTION 'Contact number must be between 7 and 20 digits.';
    END IF;

    -- 7. Mandatory DPDP Consent
    IF (to_jsonb(NEW) ? 'dpdp_consent') THEN
        IF (to_jsonb(NEW) ->> 'dpdp_consent')::text NOT IN ('true', 't', '1') THEN
            RAISE EXCEPTION 'Privacy consent must be accepted to submit inquiry.';
        END IF;
    END IF;

    -- 8. Timestamps
    NEW.created_at := coalesce(NEW.created_at, now());
    NEW.dpdp_consent_timestamp := coalesce(NEW.dpdp_consent_timestamp, now());

    RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_validate_inquiry ON public.inquiries;
CREATE TRIGGER trg_validate_inquiry
BEFORE INSERT OR UPDATE ON public.inquiries
FOR EACH ROW
EXECUTE FUNCTION public.fn_validate_inquiry();

-- ==============================================================================
-- 4. Enable Row Level Security (RLS) - Data Stays 100% Protected
-- ==============================================================================
ALTER TABLE public.inquiries ENABLE ROW LEVEL SECURITY;

-- Clean Up Existing Policies
DROP POLICY IF EXISTS "Allow public insert to inquiries" ON public.inquiries;
DROP POLICY IF EXISTS "Public can submit inquiries" ON public.inquiries;
DROP POLICY IF EXISTS "Public can view inquiries" ON public.inquiries;
DROP POLICY IF EXISTS "Admin can view inquiries" ON public.inquiries;
DROP POLICY IF EXISTS "Authenticated admin can view inquiries" ON public.inquiries;
DROP POLICY IF EXISTS "Authenticated admin can update inquiries" ON public.inquiries;
DROP POLICY IF EXISTS "Authenticated admin can delete inquiries" ON public.inquiries;
DROP POLICY IF EXISTS "Service role can manage inquiries" ON public.inquiries;

-- ==============================================================================
-- 5. Inquiries Policies
-- ==============================================================================
-- Public (anon) can ONLY insert new inquiries (Write-only, 0% read leak)
CREATE POLICY "Allow public insert to inquiries" 
ON public.inquiries 
FOR INSERT 
TO anon, authenticated, service_role 
WITH CHECK (true);

-- Authenticated Admin can view, update status, and manage inquiries
CREATE POLICY "Authenticated admin can view inquiries"
ON public.inquiries
FOR SELECT
TO authenticated
USING (true);

CREATE POLICY "Authenticated admin can update inquiries"
ON public.inquiries
FOR UPDATE
TO authenticated
USING (true)
WITH CHECK (true);

CREATE POLICY "Authenticated admin can delete inquiries"
ON public.inquiries
FOR DELETE
TO authenticated
USING (true);

-- Service Role Full Access
CREATE POLICY "Service role can manage inquiries" 
ON public.inquiries 
FOR ALL 
TO service_role 
USING (true) 
WITH CHECK (true);

-- ==============================================================================
-- 6. Gallery Table & RLS Policies (Catalog Protection)
-- ==============================================================================
CREATE TABLE IF NOT EXISTS public.gallery (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    description TEXT,
    category TEXT DEFAULT 'farms' CHECK (category IN ('farms', 'harvest', 'logistics', 'products', 'packaging')),
    image_url TEXT NOT NULL,
    file_size BIGINT DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE public.gallery ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Public can view gallery" ON public.gallery;
DROP POLICY IF EXISTS "Authenticated admin can modify gallery" ON public.gallery;
DROP POLICY IF EXISTS "Service role can modify gallery" ON public.gallery;

-- Website visitors can ONLY read gallery photos (No unauthorized insertions or defacement)
CREATE POLICY "Public can view gallery" 
ON public.gallery 
FOR SELECT 
TO anon, authenticated, service_role 
USING (true);

-- Logged-in admin can insert, update, and delete gallery photos
CREATE POLICY "Authenticated admin can modify gallery" 
ON public.gallery 
FOR ALL 
TO authenticated 
USING (true) 
WITH CHECK (true);

-- Service role full access
CREATE POLICY "Service role can modify gallery" 
ON public.gallery 
FOR ALL 
TO service_role 
USING (true) 
WITH CHECK (true);

-- ==============================================================================
-- 7. Two-Factor Authentication (MFA / Microsoft Authenticator) Verification RPC
-- ==============================================================================
CREATE OR REPLACE FUNCTION public.verify_admin_mfa(p_code TEXT)
RETURNS BOOLEAN
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
    v_clean_code TEXT := regexp_replace(coalesce(p_code, ''), '\s+', '', 'g');
    v_secret TEXT;
    v_backup_codes TEXT;
    v_key_bytes BYTEA;
    v_counter BIGINT;
    v_counter_bytes BYTEA;
    v_hash BYTEA;
    v_offset INT;
    v_truncated BIGINT;
    v_totp INT;
    v_totp_str TEXT;
    v_diff INT;
    v_alphabet TEXT := 'ABCDEFGHIJKLMNOPQRSTUVWXYZ234567';
    v_cleaned TEXT;
    v_val INT;
    v_bits INT;
    v_i INT;
    v_idx INT;
    v_byte INT;
BEGIN
    IF length(v_clean_code) < 6 THEN
        RETURN FALSE;
    END IF;

    -- Fetch 2FA secret from users table
    SELECT two_factor_secret, two_factor_backup_codes
    INTO v_secret, v_backup_codes
    FROM public.users
    WHERE role = 'admin' OR username = 'admin'
    LIMIT 1;

    -- Default fallback secret if user record does not exist
    IF v_secret IS NULL THEN
        v_secret := 'BM6P52QVLSCQU63M5ZQ6SMGXRQV5LCUD';
    END IF;

    -- Check if code matches emergency backup code
    IF v_backup_codes IS NOT NULL AND v_backup_codes ILIKE '%' || v_clean_code || '%' THEN
        RETURN TRUE;
    END IF;

    -- Base32 decode the secret key into bytes
    v_cleaned := upper(rtrim(v_secret, '='));
    v_key_bytes := '\x'::bytea;
    v_val := 0;
    v_bits := 0;

    FOR v_i IN 1..length(v_cleaned) LOOP
        v_idx := position(substr(v_cleaned, v_i, 1) in v_alphabet) - 1;
        IF v_idx >= 0 THEN
            v_val := (v_val << 5) | v_idx;
            v_bits := v_bits + 5;
            IF v_bits >= 8 THEN
                v_byte := (v_val >> (v_bits - 8)) & 255;
                v_key_bytes := v_key_bytes || decode(lpad(to_hex(v_byte), 2, '0'), 'hex');
                v_bits := v_bits - 8;
            END IF;
        END IF;
    END LOOP;

    -- RFC 6238 counter (30-second time interval)
    v_counter := floor(extract(epoch from now()) / 30)::bigint;

    -- Drift tolerance: window of -1, 0, +1 (current ± 30 seconds)
    FOR v_diff IN -1..1 LOOP
        -- Type-safe 8-byte big-endian counter using to_hex and decode
        v_counter_bytes := decode(lpad(to_hex(v_counter + v_diff), 16, '0'), 'hex');

        -- HMAC-SHA1
        v_hash := hmac(v_counter_bytes, v_key_bytes, 'sha1');

        -- Dynamic truncation
        v_offset := get_byte(v_hash, 19) & 15;
        v_truncated := ((get_byte(v_hash, v_offset) & 127) << 24) |
                       ((get_byte(v_hash, v_offset + 1) & 255) << 16) |
                       ((get_byte(v_hash, v_offset + 2) & 255) << 8) |
                       (get_byte(v_hash, v_offset + 3) & 255);

        v_totp := v_truncated % 1000000;
        v_totp_str := lpad(v_totp::text, 6, '0');

        IF v_totp_str = v_clean_code THEN
            RETURN TRUE;
        END IF;
    END LOOP;

    RETURN FALSE;
END;
$$;

-- ==============================================================================
-- 8. PostgreSQL Permissions & Grants
-- ==============================================================================
GRANT USAGE ON SCHEMA public TO anon, authenticated, service_role;

-- Public (anon) is restricted to INSERT ONLY on inquiries (zero read leak)
GRANT INSERT ON TABLE public.inquiries TO anon;

-- Authenticated Admin gets full access
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.inquiries TO authenticated;

-- Gallery: anon gets SELECT ONLY, authenticated gets full CRUD
GRANT SELECT ON TABLE public.gallery TO anon;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.gallery TO authenticated;

-- Service role full access
GRANT ALL ON TABLE public.inquiries TO service_role;
GRANT ALL ON TABLE public.gallery TO service_role;

-- Sequences & MFA function execution permissions
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.verify_admin_mfa(TEXT) TO anon, authenticated, service_role;
