-- ============================================================================
-- VPSA YOGA - Supabase PostgreSQL Database Schema & Migration Script
-- Run this script directly in the Supabase SQL Editor (https://supabase.com/dashboard)
-- ============================================================================

-- 1. Create Tables

CREATE TABLE IF NOT EXISTS public.users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username TEXT UNIQUE NOT NULL,
    password_hash TEXT NOT NULL,
    email TEXT UNIQUE NOT NULL,
    role TEXT DEFAULT 'admin' CHECK (role IN ('admin', 'editor')),
    two_factor_secret TEXT,
    two_factor_enabled INTEGER DEFAULT 0,
    two_factor_temp_secret TEXT,
    two_factor_backup_codes TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    last_login_at TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS public.products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slug TEXT UNIQUE NOT NULL,
    name_en TEXT NOT NULL,
    name_ta TEXT NOT NULL,
    name_hi TEXT NOT NULL,
    name_ml TEXT NOT NULL,
    name_te TEXT NOT NULL,
    name_ar TEXT NOT NULL,
    tagline TEXT NOT NULL,
    health_benefits TEXT NOT NULL,
    taste_profile TEXT NOT NULL,
    shelf_life TEXT NOT NULL,
    packing_specs TEXT NOT NULL,
    ideal_temperature TEXT NOT NULL,
    image_url TEXT NOT NULL,
    is_featured INTEGER DEFAULT 1,
    sort_order INTEGER DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.gallery (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    description TEXT,
    category TEXT DEFAULT 'farms' CHECK (category IN ('farms', 'harvest', 'logistics', 'products', 'packaging')),
    image_url TEXT NOT NULL,
    file_size BIGINT DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.inquiries (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name TEXT NOT NULL,
    email TEXT NOT NULL,
    country_code TEXT DEFAULT '+91',
    mobile_number TEXT NOT NULL,
    company_name TEXT,
    product_variety TEXT,
    quantity TEXT,
    destination TEXT,
    message TEXT NOT NULL,
    status TEXT DEFAULT 'new' CHECK (status IN ('new', 'contacted', 'in_review', 'completed')),
    ip_address TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.audit_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_type TEXT NOT NULL,
    description TEXT NOT NULL,
    user_id BIGINT REFERENCES public.users(id) ON DELETE SET NULL,
    ip_address TEXT,
    user_agent TEXT,
    severity TEXT DEFAULT 'INFO' CHECK (severity IN ('INFO', 'WARN', 'CRITICAL')),
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Indexes for Optimized Query Performance
CREATE INDEX IF NOT EXISTS idx_products_slug ON public.products(slug);
CREATE INDEX IF NOT EXISTS idx_gallery_category ON public.gallery(category);
CREATE INDEX IF NOT EXISTS idx_inquiries_status ON public.inquiries(status);
CREATE INDEX IF NOT EXISTS idx_inquiries_created ON public.inquiries(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_audit_logs_event ON public.audit_logs(event_type);

-- 3. Row Level Security (RLS) Policies
ALTER TABLE public.products ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.gallery ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.inquiries ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.users ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.audit_logs ENABLE ROW LEVEL SECURITY;

-- Products: Public Read, Service/Admin Write
DROP POLICY IF EXISTS "Public can view products" ON public.products;
CREATE POLICY "Public can view products" ON public.products FOR SELECT USING (true);

DROP POLICY IF EXISTS "Service role can modify products" ON public.products;
CREATE POLICY "Service role can modify products" ON public.products FOR ALL USING (true);

-- Gallery: Public Read, Service/Admin Write
DROP POLICY IF EXISTS "Public can view gallery" ON public.gallery;
CREATE POLICY "Public can view gallery" ON public.gallery FOR SELECT USING (true);

DROP POLICY IF EXISTS "Service role can modify gallery" ON public.gallery;
CREATE POLICY "Service role can modify gallery" ON public.gallery FOR ALL USING (true);

-- Inquiries: Deny Anon/Public direct REST access (All submissions and management must route through Node backend)
DROP POLICY IF EXISTS "Public can submit inquiries" ON public.inquiries;
DROP POLICY IF EXISTS "Public can view inquiries" ON public.inquiries;
DROP POLICY IF EXISTS "Service role can manage inquiries" ON public.inquiries;
CREATE POLICY "Service role can manage inquiries" ON public.inquiries FOR ALL USING (true);

-- Users & Audit Logs: Service/Admin Access
DROP POLICY IF EXISTS "Service role can manage users" ON public.users;
CREATE POLICY "Service role can manage users" ON public.users FOR ALL USING (true);

DROP POLICY IF EXISTS "Service role can manage audit logs" ON public.audit_logs;
CREATE POLICY "Service role can manage audit logs" ON public.audit_logs FOR ALL USING (true);

-- 4. Initial Seed Data: Banana Products
INSERT INTO public.products (slug, name_en, name_ta, name_hi, name_ml, name_te, name_ar, tagline, health_benefits, taste_profile, shelf_life, packing_specs, ideal_temperature, image_url, is_featured, sort_order)
VALUES
(
    'red-banana',
    'Red Banana (Sevvazhai)',
    'செவ்வாழை (Red Banana)',
    'लाल केला (Red Banana)',
    'ചെങ്കദളി (Red Banana)',
    'ఎరుపు అరటి (Red Banana)',
    'موز أحمر (Red Banana)',
    'High Nutrient & Antioxidant Superfruit',
    'Rich in potassium, magnesium, vitamin B6, and significantly higher levels of vitamin C and beta-carotene than standard yellow bananas. Boosts immunity, aids blood pressure regulation, and enhances ocular health.',
    'Distinctively sweet with delicate berry-like nuances and velvety texture.',
    '6 to 8 Days at 13-14°C',
    '7kg / 13kg Export Grade Corrugated Box, Foam Wrapped',
    '13.0°C - 14.5°C',
    '/images/products/red-banana.jpg',
    1,
    1
),
(
    'poovan-banana',
    'Poovan Banana',
    'பூவன் வாழை (Poovan)',
    'पूवन केला (Poovan)',
    'പൂവൻ പഴം (Poovan)',
    'పూవన్ అరటి (Poovan)',
    'موز بوفان (Poovan)',
    'Gentle on Stomach & High Dietary Fiber',
    'Rich in soluble dietary fiber, making it gentle on the stomach and exceptionally easy to digest. Enhances intestinal microflora, relieves acidity, and provides quick, sustained natural energy.',
    'Pleasantly tangy-sweet with firm pulp and distinct pleasant aroma.',
    '7 to 10 Days at 13-14°C',
    '10kg / 15kg Telescopic Cartons with Polyethylene Liner',
    '13.5°C - 14.0°C',
    '/images/products/poovan-banana.jpg',
    1,
    2
),
(
    'nendran-banana',
    'Nendran Banana (Kerala Plantain)',
    'நேந்திரன் வாழை (Nendran)',
    'नेन्द्रन केला (Nendran)',
    'നേന്ത്രപ്പഴം (Nendran)',
    'నేంద్రన్ అరటి (Nendran)',
    'موز نيندران (Nendran)',
    'Kerala Specialty for Culinary & Superfood Vitality',
    'High in resistant starch (when slightly green), dietary fiber, potassium, and Vitamin B6, making them exceptionally beneficial for gut microbiota, insulin sensitivity, and cardiovascular health.',
    'Rich, firm, subtly sweet with versatile culinary suitability for chips, steaming, and ripe consumption.',
    '8 to 12 Days at 13-14°C',
    '12kg / 18kg Heavy Duty Export Crates with Ethylene Absorbers',
    '13.0°C - 14.0°C',
    '/images/products/nendran-banana.jpg',
    1,
    3
),
(
    'yelakki-banana',
    'Yelakki / Elakki Banana',
    'ஏலக்கி வாழை (Yelakki)',
    'इलायची केला (Yelakki)',
    'ഏലക്കി പഴം (Yelakki)',
    'ఏలక్కి అరటి (Yelakki)',
    'موز يلاكي (Yelakki)',
    'Pocket-Sized Intense Honey-Sweet Aroma',
    'Small, highly sweet, and aromatic variety widely cultivated in South India. Packed with concentrated energy, calcium, vitamin C, and dietary fiber. Ideal for children, athletes, and gourmet desserts.',
    'Intense honeyed sweetness with a rich floral bouquet and firm, fragrant flesh.',
    '5 to 7 Days at 13-14°C',
    '5kg / 10kg Premium Master Cartons with Cushioning Trays',
    '13.5°C - 14.5°C',
    '/images/products/yelakki-banana.jpg',
    1,
    4
),
(
    'karpuravalli-banana',
    'Karpuravalli Banana',
    'கற்பூரவள்ளி (Karpuravalli)',
    'कर्पूरावल्ली (Karpuravalli)',
    'കർപ്പൂരവള്ളി (Karpuravalli)',
    'కర్పూరవల్లి (Karpuravalli)',
    'موز كارفورافالي (Karpuravalli)',
    'Drought-Tolerant High Natural Sugar Profile',
    'Naturally endowed with high sugar content, rich in dietary fiber, potassium, and beneficial phytonutrients that support healthy digestion and rapid cellular rejuvenation.',
    'Extremely sweet with a distinct refreshing cooling aftertaste and soft juicy pulp.',
    '6 to 9 Days at 13-14°C',
    '10kg / 15kg Corrugated Master Cartons with Air Vents',
    '13.0°C - 14.0°C',
    '/images/products/karpuravalli-banana.jpg',
    1,
    5
),
(
    'rasthali-banana',
    'Rasthali / Silk Banana',
    'ரஸ்தாளி (Rasthali)',
    'रसथली (Rasthali)',
    'രസ്താലി (Rasthali)',
    'రస్తాలి (Rasthali)',
    'موز راسثالي (Rasthali)',
    'Delicate Gourmet Silk Texture & Aristocratic Fragrance',
    'Contains balanced minerals, vitamin B-complex, and prebiotic fiber that foster gastrointestinal comfort and support nervous system regulation.',
    'Silky, melt-in-mouth mouthfeel with delicate sub-acid sweetness and floral aroma.',
    '4 to 6 Days at 13-14°C',
    '7kg / 10kg Ventilated Rigid Boxes with Protective Spacers',
    '13.5°C - 14.5°C',
    '/images/products/rasthali-banana.jpg',
    1,
    6
),
(
    'robusta-banana',
    'Robusta Cavendish Banana',
    'ரோபஸ்டா கேவென்டிஷ் (Robusta)',
    'रोबस्टा केला (Robusta)',
    'റോബസ്റ്റ (Robusta)',
    'రోబస్టా అరటి (Robusta)',
    'موز روبوستا كافنديش (Robusta)',
    'Global Commercial Workhorse & High Calorie Energy',
    'A powerhouse of quick carbohydrates, magnesium, vitamin B6, and potassium. Widely demanded for athletic nutrition, commercial food processing, and global retail distribution.',
    'Smooth, creamy sweetness with uniform cylindrical shape and heavy bunch density.',
    '10 to 14 Days at 13-14°C',
    '13kg / 18.14kg (40lb) International Standard Vacuum-Packed Cartons',
    '13.0°C - 13.5°C',
    '/images/products/robusta-banana.jpg',
    1,
    7
),
(
    'monthan-banana',
    'Monthan Cooking Banana',
    'மொந்தன் வாழை (Monthan)',
    'मोंथन केला (Monthan)',
    'മൊന്തൻ കായ (Monthan)',
    'మొంతన్ అరటి (Monthan)',
    'موز مونثان للطبخ (Monthan)',
    'Premier Culinary Banana for Savory Gastronomy',
    'High in prebiotic dietary fiber, resistant starches, and essential minerals. Excellent for blood sugar management due to low glycemic impact in savory cooking preparations.',
    'Savory, starchy, firm texture perfectly suited for South Indian curries, stir-fries, and chips.',
    '12 to 18 Days at 13-15°C',
    '15kg / 20kg Heavy Duty Crates / Sacks for Wholesale Markets',
    '13.0°C - 15.0°C',
    '/images/products/monthan-banana.jpg',
    1,
    8
)
ON CONFLICT (slug) DO NOTHING;

-- 5. Initial Seed Data: Operations Gallery
INSERT INTO public.gallery (title, description, category, image_url, file_size)
VALUES
('Lush Plantation Harvest', 'Direct harvesting operations from accredited farms across South India.', 'farms', '/images/products/page_1_img_1.jpg', 245000),
('Precision Fruit Grading', 'Hands-on quality grading, bunch washing, and size classification.', 'harvest', '/images/products/page_2_img_2.jpg', 280000),
('Temperature-Controlled Reefer Fleet', 'Refrigerated logistics maintaining strict 13-14°C cold chain.', 'logistics', '/images/products/page_3_img_1.jpg', 310000),
('Export Packaging Center', 'Hygienic corrugated cartons with ethylene absorbing sachets.', 'packaging', '/images/products/page_4_img_1.jpg', 290000),
('Pan-India Dispatch Hub', 'Daily wholesale dispatches across South India wholesale markets.', 'logistics', '/images/products/page_5_img_1.jpg', 275000),
('Farm-Fresh Handover', 'Consistent daily supply directly to hypermarkets and wholesale vendors.', 'farms', '/images/products/page_6_img_1.jpg', 260000)
ON CONFLICT DO NOTHING;
